# Generated by Django 6.0.7 on 2026-08-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_email', models.EmailField(max_length=254)),
                ('total_experience', models.DecimalField(decimal_places=1, max_digits=4)),
                ('primary_skill', models.CharField(max_length=100)),
                ('secondary_skill', models.CharField(blank=True, max_length=100)),
                ('cm_name', models.CharField(max_length=100)),
                ('profile_status', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('date_shared', models.DateField()),
                ('project_owner', models.CharField(max_length=100)),
            ],
        ),
    ]
